# Generated by Django 4.0.4 on 2022-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bill',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkIn',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkOut',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='custOccupation',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customerEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customerName',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='numberOfNight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='roomNumber',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
