# Generated by Django 4.0.4 on 2022-06-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_bill_alter_booking_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='roomNumber',
            field=models.CharField(max_length=10000),
        ),
    ]
