# Generated by Django 4.0.4 on 2022-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_booking_numberofnight_alter_booking_roomnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='roomNumber',
        ),
        migrations.AddField(
            model_name='booking',
            name='rNumber',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='numberOfNight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
